### PR TITLE
Check ws.readyState at ping

### LINKED ISSUE #384: Unecesarry ping when WebSocket is not ready
`WebsocketClient` sends unncesarry `ping` and `pong` when WebSocket exists, but it's not ready .
It results in unnecesarry errors like:

```text
error: Failed to send WS ping {
  category: 'binance-ws',
  wsKey: 'spot_userData__rE3a2TtbzbjRRhrQ5i7r1xrrPof2hengrfLTcEeI1bWFCEz4L3Yj5RixKpkB',
  exception: Error: WebSocket is not open: readyState 0 (CONNECTING)
```

This situation can be avoided by testing `readyState` to be `OPEN` before sending the `ping` and `pong`.

### PR DESCRIPTION
**Pull request by dutu**
## Summary
`WebsocketClient`, before sending ping and pong, will make sure the WebSocket's `readyState`  is `OPEN`. This will avoid unnecesarry errors when sending ping/pong while WebSocket is not ready (such as `CONNECTING` or `CLOSING` states).

## Additional Information
Closes #384

### CODE REVIEW

File: src/websocket-client.ts [hunk 1]
```diff
@@ -296,8 +296,10 @@ export class WebsocketClient extends EventEmitter {
       }
 
       // Binance allows unsolicited pongs, so we send both (though we expect a pong in response to our ping if the connection is still alive)
-      ws.ping();
-      ws.pong();
+      if (ws.readyState === 1) {
+        ws.ping();
+        ws.pong();
+      }
```
Comment (tiagosiebler) [inline src/websocket-client.ts:302]: Just in case there's a troubleshooting need in future:

```suggestion
      if (ws.readyState === 1) {
        ws.ping();
        ws.pong();
      } else {
        this.logger.silly(
          `WS ready state not open - refusing to send WS ping`,
          { ...loggerCategory, wsKey, readyState: ws?.readyState },
        );
      }
```

**Review by tiagosiebler — CHANGES_REQUESTED** [review]
Thanks for the PR. Small suggestion - probably over kill, but just in case we ever need to investigate. Silly/debug logs are disabled by default anyway, so it's not swapping one error for another.

File: src/websocket-client.ts (hunk 1 above)
Comment (dutu) [reply src/websocket-client.ts:302]: Yeah, it makes sense.

I can also see a case if/when the WebSocket gets stuck in state different than OPEN (not sure if it could ever happen, but if...), pongTimeout never occurs (since it is cleared before `tryWsPing()` is called), and there would be no indication of any problem.

**Review by tiagosiebler — APPROVED** [review]
LGTM, thanks!
